### ISSUE TITLE
22/01/2018

### ISSUE THREAD

**Issue by baolo073** [buiphucminhtam/ScreenCaptureEasy#1]
1/ Toast lúc nào cũng  "save 3.png"
2/ Tiếng Anh và tiếng Việt không đồng bộ, tức là chọn tiếng Anh thì nên chuyển toàn bộ ngôn ngữ của app sang tiếng Anh và ngược lại
3/ Phần chỉnh chụp yên lặng chưa thấy có công dụng vì lúc bật hay không bật nó cũng yên lặng
4/ Phần giao diện trong cài đặt, chữ màu đỏ (tiêu đề) nên cho nổi bật (in đậm, in hoa)
5/ Phần show ảnh chụp đc cho người dùng xem, cái list nên chỉnh nhỏ lại để cho tấm ảnh view ở trên to ra nhìn sẽ cân đối hơn

**Comment by buiphucminhtam** [comment]
1/ Thiết bị nào, api nào bị lỗi cần nêu rõ để có thể dễ fix vì hiện tại chạy trên emulator (galaxy nexus api 22) + thiết bị thật (samsung grand prime 7.1.2) vẫn hoạt động bình thường.
2/ Đã update thêm ngôn ngữ english

**Comment by baolo073** [comment]
31/01/2018
1/ Sửa dòng Toast lại thành "Saved"
2/ Chưa đổi phần ui của setting
3/ Phần ngôn ngữ, chọn vi sao nó vẫn eng
Hết
